import {
  PERMISSIONS,
  type Permission,
} from "./permissions.js";

// Maps role names to the permissions granted to each role.
export const ROLE_PERMISSIONS: Record<
  string,
  readonly Permission[]
> = {
  WORKER: [
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
  ],

  ADMIN: [
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.MATERIALS_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.HISTORY_READ,
  ],
};